version: "0.1"
user: vishnurv2
key: 2dEK8rin7XC3cChRqccFoMlcC9FwPNloQdqV9c4y7vFUAnAB18
testSuites: []
pre: [npm install, npx playwright install]
jobLabel:
- Sparsh
- playwright
runson: win
autosplit: true
concurrency: 4
testDiscovery:
  autosubset: true
  command: grep -lr 'test' tests
  mode: dynamic
  type: raw
testRunnerCommand: npx playwright test $test
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
cacheDirectories:
- node_modules
cacheKey: '{{ checksum "package-lock.json" }}'
maxRetries: 1
jobID: 14e89a65-ea52-49f3-aa09-700ca85f7414
uploadArtefacts:
- name: playwright-report
  path:
  - playwright-report/**
codeDirectory: playwright-test
framework:
  name: ""
  flags: []
  discoveryType: ""
  workingDirectory: ""
  isTestNGXMLSuite: false
  defaultReports: true
cypress: false
betaFeature:
  setPartiallyCompletedAsCompleted: false
testType: playwright
